"""economia da despensa no item da lista

Revision ID: 1c737f5ba65d
Revises: 4c9cbf91e535
Create Date: 2026-09-16 11:34:57.140894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c737f5ba65d'
down_revision: Union[str, Sequence[str], None] = '4c9cbf91e535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('pantry_savings', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'pantry_savings')
    # ### end Alembic commands ###
