"""confirmacao do produto no item do plano e desconto da despensa na lista

Revision ID: 236c6cedc017
Revises: 340a72bb7130
Create Date: 2026-09-08 20:50:02.920545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236c6cedc017'
down_revision: Union[str, Sequence[str], None] = '340a72bb7130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_items', sa.Column('product_id', sa.Uuid(), nullable=True))
    op.add_column('plan_items', sa.Column('match_score', sa.Numeric(precision=4, scale=3), nullable=True))
    op.create_index(op.f('ix_plan_items_product_id'), 'plan_items', ['product_id'], unique=False)
    op.create_foreign_key(op.f('fk_plan_items_product_id_products'), 'plan_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.add_column('shopping_list_items', sa.Column('quantity_from_pantry', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'quantity_from_pantry')
    op.drop_constraint(op.f('fk_plan_items_product_id_products'), 'plan_items', type_='foreignkey')
    op.drop_index(op.f('ix_plan_items_product_id'), table_name='plan_items')
    op.drop_column('plan_items', 'match_score')
    op.drop_column('plan_items', 'product_id')
    # ### end Alembic commands ###
