"""item avulso na lista de compras

Revision ID: 45f461c0d4c0
Revises: 1c737f5ba65d
Create Date: 2026-09-30 11:03:52.662821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45f461c0d4c0'
down_revision: Union[str, Sequence[str], None] = '1c737f5ba65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_list_items', 'plan_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('uq_shopping_list_items_avulso', 'shopping_list_items', ['shopping_list_id', 'product_id'], unique=True, postgresql_where=sa.text('plan_item_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_shopping_list_items_avulso', table_name='shopping_list_items', postgresql_where=sa.text('plan_item_id IS NULL'))
    # O item avulso não cabe no schema anterior: lá toda linha vem de um item
    # do plano. Apagar é a única volta possível, e some só com o que a pessoa
    # acrescentou à compra — a prescrição e os itens que vieram dela ficam.
    op.execute('DELETE FROM shopping_list_items WHERE plan_item_id IS NULL')
    op.alter_column('shopping_list_items', 'plan_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
