"""item comprado na lista de compras

Revision ID: 4c9cbf91e535
Revises: d9e60d044691
Create Date: 2026-09-16 10:48:29.973759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9cbf91e535'
down_revision: Union[str, Sequence[str], None] = 'd9e60d044691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_list_items', sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_list_items', 'purchased_at')
    # ### end Alembic commands ###
