"""senha obrigatoria no usuario

Revision ID: d9e60d044691
Revises: 236c6cedc017
Create Date: 2026-09-08 22:45:52.541441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e60d044691'
down_revision: Union[str, Sequence[str], None] = '236c6cedc017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Usuário sem senha não consegue entrar, então não deveria existir. Se houver
    alguma linha assim, esta migração falha de propósito: decidir o que fazer
    com a conta de uma pessoa é decisão de quem opera, não da migração.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
