"""criacao das tabelas iniciais

Revision ID: e6f844d31c0c
Revises: 
Create Date: 2026-08-25 20:39:38.631553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f844d31c0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('chain', sa.String(length=120), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('is_fictitious', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('cnpj', name=op.f('uq_markets_cnpj'))
    )
    op.create_index(op.f('ix_markets_city'), 'markets', ['city'], unique=False)
    op.create_index(op.f('ix_markets_state_code'), 'markets', ['state_code'], unique=False)
    op.create_table('products',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=True),
    sa.Column('package_size', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('package_unit', sa.Enum('g', 'kg', 'ml', 'l', 'unidade', name='measurement_unit'), nullable=True),
    sa.Column('base_unit', sa.Enum('kg', 'l', 'unidade', name='base_unit'), nullable=False),
    sa.Column('barcode', sa.String(length=14), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('is_fictitious', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('barcode', name=op.f('uq_products_barcode')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_normalized_name'), 'products', ['normalized_name'], unique=False)
    op.create_table('recipes',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('prep_minutes', sa.Integer(), nullable=True),
    sa.Column('is_fictitious', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes')),
    sa.UniqueConstraint('slug', name=op.f('uq_recipes_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('meal_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('nutritionist_name', sa.String(length=255), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consent_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_index(op.f('ix_meal_plans_user_id'), 'meal_plans', ['user_id'], unique=False)
    op.create_table('price_records',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('market_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.Enum('g', 'kg', 'ml', 'l', 'unidade', name='measurement_unit'), nullable=False),
    sa.Column('price_per_base_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin', sa.Enum('nfce', 'scraping', 'usuario', 'seed', name='price_origin'), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('nfce_access_key', sa.String(length=44), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_price_records_market_id_markets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_records_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_price_records_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_records')),
    sa.UniqueConstraint('nfce_access_key', 'product_id', name='uq_price_records_nota_produto')
    )
    op.create_index(op.f('ix_price_records_market_id'), 'price_records', ['market_id'], unique=False)
    op.create_index('ix_price_records_produto_regiao_data', 'price_records', ['product_id', 'state_code', 'city', 'collected_at'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('g', 'kg', 'ml', 'l', 'unidade', name='measurement_unit'), nullable=False),
    sa.Column('optional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_recipe_ingredients_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients')),
    sa.UniqueConstraint('recipe_id', 'product_id', name='uq_recipe_ingredients_receita_produto')
    )
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('normalized_description', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('g', 'kg', 'ml', 'l', 'unidade', name='measurement_unit'), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'confirmado', 'nao_identificado', name='plan_item_status'), server_default='pendente', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], name=op.f('fk_plan_items_meal_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items')),
    sa.UniqueConstraint('meal_plan_id', 'position', name='uq_plan_items_plano_ordem')
    )
    op.create_index(op.f('ix_plan_items_meal_plan_id'), 'plan_items', ['meal_plan_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('estimated_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], name=op.f('fk_shopping_lists_meal_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_lists'))
    )
    op.create_index(op.f('ix_shopping_lists_meal_plan_id'), 'shopping_lists', ['meal_plan_id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('shopping_list_id', sa.Uuid(), nullable=False),
    sa.Column('plan_item_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('g', 'kg', 'ml', 'l', 'unidade', name='measurement_unit'), nullable=False),
    sa.Column('packages_needed', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_reference_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_origin', sa.Enum('nfce', 'scraping', 'usuario', 'seed', name='price_origin'), nullable=True),
    sa.Column('price_confidence', sa.Enum('atual', 'recente', 'estimativa', name='price_confidence'), nullable=True),
    sa.Column('price_sample_size', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_item_id'], ['plan_items.id'], name=op.f('fk_shopping_list_items_plan_item_id_plan_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_shopping_list_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_list_items_shopping_list_id_shopping_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_items')),
    sa.UniqueConstraint('shopping_list_id', 'plan_item_id', name='uq_shopping_list_items_lista_item')
    )
    op.create_index(op.f('ix_shopping_list_items_shopping_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_list_items_shopping_list_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index(op.f('ix_shopping_lists_meal_plan_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_plan_items_meal_plan_id'), table_name='plan_items')
    op.drop_table('plan_items')
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_price_records_produto_regiao_data', table_name='price_records')
    op.drop_index(op.f('ix_price_records_market_id'), table_name='price_records')
    op.drop_table('price_records')
    op.drop_index(op.f('ix_meal_plans_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_products_normalized_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_markets_state_code'), table_name='markets')
    op.drop_index(op.f('ix_markets_city'), table_name='markets')
    op.drop_table('markets')

    # O DROP TABLE do Postgres não remove os tipos ENUM criados junto com as
    # tabelas. Sem estas linhas, um `downgrade base` seguido de `upgrade head`
    # falha com "type measurement_unit already exists".
    for nome_do_tipo in (
        'measurement_unit',
        'base_unit',
        'price_origin',
        'plan_item_status',
        'price_confidence',
    ):
        op.execute(f'DROP TYPE IF EXISTS {nome_do_tipo}')
    # ### end Alembic commands ###
